### PR TITLE
Glyma.gillman tetlow 2011.yml

### PR DESCRIPTION
**Pull request by jd-campbell**
Edited file during Monday meeting

Please review

### CODE REVIEW

**Review by StevenCannon-USDA — COMMENTED** [review]
This one looks close, but the comments need work. Each comment should be precise and factual -- not general or speculative.
The first comment: `involved in upregulating the UF3GT expression, leading to brown hilum color` ... think about the role of the wild-type gene vs. the mutated gene. Which state is associated with which color? Look at the paragraph beginning "All of the Glycine soja accessions in the USDA ..."
The second and third comments -- I don't think those belong. They are vague space-filler comments.

**Review by maxglycine — CHANGES_REQUESTED** [review]
The ontology term TO:0000838 Seed coat morphology trait is redundant.  It a parent term to TO:0000190 seed coat color.

The term TO:0000890 is Seed coat proportion.  TO:0000190 is seed coat color see https://browser.planteome.org/amigo/term/TO:0000190#display-lineage-tab

**Comment by ScottKalberer** [comment]
I completed the changes to the ontology terms requested by Rex Nelson.  I also tried to improve the comments and phenotype description based on the abstract - I would like to read the paper more carefully and improve these lines tomorrow.  I also corrected some minor issues with the citation formats.

**Comment by StevenCannon-USDA** [comment]
I am approving this and will merge to main. It has received a lot of attention and changes and I think is acceptable now.

**Pull request merged**
