### PR TITLE
Snf review roy2020

### PR DESCRIPTION
**Pull request by StevenCannon-USDA**
I changed all yml files, adding a field "scientific_name" to each (since some files describe genes from several species), and added a two-letter prefix to each gene_symbol - for example, Gm, Mt, Lj. Also removed two very incomplete files.

### CODE REVIEW

**Comment by StevenCannon-USDA** [comment]
@ScottKalberer - I am converting this PR to draft status, since I see more changes that I would like to make.

**Comment by StevenCannon-USDA** [comment]
Scott - this is ready for your review, please. However, I recommend NOT looking at each change, since I changed ALL files (79 I believe)! We can discuss the types of changes and make further corrections incrementally as needed.

**Review by ScottKalberer — APPROVED** [review]
I agree with your deletion of these two gene function files.

**Review by ScottKalberer — APPROVED** [review]
I agree with this addition of the field "scientific name" and the prefixing of the Genus-species to the gene symbols.  I also see that the field classical locus is being eliminated.

**Review by ScottKalberer — APPROVED** [review]
I accept this addition of the gensp prefix to the titles of YML files and the splitting of multi-species files into single-species files.

**Review by ScottKalberer — APPROVED** [review]

**Pull request merged**
