### PR TITLE
Create glyma.Kovinich_Saleem_2012.yml

### PR DESCRIPTION
**Pull request by ellatownsend90**
first submission pls review thank you so much

### CODE REVIEW

**Review by ScottKalberer — COMMENTED** [review]
I made several alterations to this file in the form of two new commits to the branch.  These include issues such as the gene_symbols for both genes, gene_symbol_long and gene_model_full_id for GmANR2, the comments and phenotype_synopses, spelling of Kovinich in the citations, adding anthocyanidin reductase ontology (not essential), and reducing the confidence levels for both genes (especially GmANR2).  I would look over these changes and see if you agree.  Steven or Jacqueline may perform final approval since my own ideas should be reviewed ideally.

**Comment by ScottKalberer** [comment]
Statements such as the following from the discussion in Kovinich, Saleem et al. (2012) reduced my scores for confidence levels - what do you all feel?  "Although gene expression analysis demonstrated
that ANR1 was highly expressed in the seed coat
compared to ANR2 (Figure 4), it remains unclear whether the
differences observed in gene expression or enzyme activity are
sufficient to explain the phenotypic variation between brown
and red-brown seed coats. Recently, a partial soybean sequence
with 86% sequence identity to the M. truncatula ANR gene was
mapped to the genomic region coding the O locus. The genes
coding ANR1 (Glyma08g06630) and ANR2 (Glyma08g06640)
were located in the same region of the Glyma1 soybean genome
sequence, further supporting that either may encode the O gene.
However, further analysis, such as gene complementation or
gene suppression, will be required to substantiate that defects in
the ANR1 gene are responsible for red-brown seed coat color
and that ANR1 may be the O gene. The possibility exists that
other regulatory, biosynthetic, or trafficking differences in the
PA pathway not related to ANR1 may be responsible for
reduced PA content in red-brown seed coats."

**Comment by ScottKalberer** [comment]
I may have messed up in deleting "classical_locus: O" from ANR1.  I had read this field as being filled out with "zero" rather than the letter "O", as in you were trying to indicate there was no classical locus.  In which case the field should have been deleted.  If there is good reason to believe ANR1 is actually the "O" classical locus this field may be restored - I need to look again on Tuesday after the federal holiday.

**Comment by jd-campbell** [comment]
> Statements such as the following from the discussion in Kovinich, Saleem et al. (2012) reduced my scores for confidence levels - what do you all feel? "Although gene expression analysis demonstrated that ANR1 was highly expressed in the seed coat compared to ANR2 (Figure 4), it remains unclear whether the differences observed in gene expression or enzyme activity are sufficient to explain the phenotypic variation between brown and red-brown seed coats. Recently, a partial soybean sequence with 86% sequence identity to the M. truncatula ANR gene was mapped to the genomic region coding the O locus. The genes coding ANR1 (Glyma08g06630) and ANR2 (Glyma08g06640) were located in the same region of the Glyma1 soybean genome sequence, further supporting that either may encode the O gene. However, further analysis, such as gene complementation or gene suppression, will be required to substantiate that defects in the ANR1 gene are responsible for red-brown seed coat color and that ANR1 may be the O gene. The possibility exists that other regulatory, biosynthetic, or trafficking differences in the PA pathway not related to ANR1 may be responsible for reduced PA content in red-brown seed coats."

@ScottKalberer I agree with you. The quoted statement above also leads me to believe there is missing elements for this gene function within the paper.

**Comment by ScottKalberer** [comment]
Did we come to a consensus regarding capitalizing the "g" as "G" in all gene model names?  As in Glyma08g06630 vs Glyma08G06630.  I was always capitalizing mine as "G" to be consistent and which I thought Steven preferred.  I don't think it's a big deal either way unless the name is going to be case-sensitive when subject to search.

**Comment by ScottKalberer** [comment]
Jacqueline appears to be in agreement regarding the confidence levels.  I just restored the classical locus and added an explanatory comment.  Would there be any other feedback before this file is approved?  Ella, would you wish to let us know if you understand and agree with all the changes I have completed?  Thanks everyone!

**Review by StevenCannon-USDA — COMMENTED** [review]
This one looks very close to ready to me, after Scott's changes.
I'd like to see the following additional changes.
`gene_model_full_id: glyma.Wm82.gnm4.ann1.Glyma.08G062000`
and
`gene_model_full_id: glyma.Wm82.gnm4.ann1.Glyma.08G062100 `

Those genes are both in this gene family, btw:
http://dev.lis.ncgr.org:50082/?family=Legume.fam3.05228

The second phenotype synopsis: "undetermined significance" is modifying "tissues", but should modify "anthocyanidin reductase", like so:
`phenotype_synopsis: An anthocyanidin reductase of undetermined significance that is found in many tissues.`

**Comment by ScottKalberer** [comment]
The latest commit on this branch completes the corrections requested by Steven Cannon regarding the two gene_model_full_id and the second phenotype synopsis.

**Review by ScottKalberer — APPROVED** [review]
I have completed all requested changes to the file glyma.Kovinich_Saleem_2012.yml.  I believe we can now merge this branch into the main and move on to other concerns.

**Pull request merged**
