### PR TITLE
Glyma.su chen 2022.yml

### PR DESCRIPTION
**Pull request by ellatownsend90**
Curated and ready for review

### CODE REVIEW

**Comment by ellatownsend90** [comment]
Ready and awaiting a review

**Review by StevenCannon-USDA — COMMENTED** [review]
This one mostly looks good to me, but I would like to see the comments be made more precise and specific.
Rather than "the role of Ft homologs is not fully understood since so many go into flowering time", let's use these points from the abstract:
```
  - GmFT3b expression was induced by photoperiod and circadian rhythm and was more responsive to long-day (LD) conditions, but there were no significant differences in flowering time between the wild-type, the GmFT3b overexpressors, and the ft3b knockouts under natural long-day, short-day, or LD conditions.
  - GmFT3b acts redundantly in flowering time regulation and may be compensated by other FT homologs in soybean.
```
For the synopsis - again, I think this should be more precise and specific. Let's use:
`phenotype_synopsis: A flowering time locus, orthologous to Arabidopsis FLOWERING LOCUS T (FT), but apparently redundant with other FT loci in soybean.`

For the gene_model_full_id, this one from assembly one is OK ... glyma.Wm82.gnm1.ann1.Glyma19g28390 ... but somewhat preferable would be one of the newer annotations. The first choice (we need to document this) would be from assembly 4 (glyma.Wm82.gnm4.ann1; `glyma.Wm82.gnm4.ann1.Glyma.19G108100`), because those genes are in the current gene families. For example, the FT genes are in this family:
http://dev.lis.ncgr.org:50082/?family=Legume.fam3.00317

So, please change gene_model_full_id to glyma.Wm82.gnm4.ann1.Glyma.19G108100

**Comment by ScottKalberer** [comment]
I have completed the corrections requested by Steven Cannon last month and added a few additions of my own as well.  The file should be ready for review and the branches that then be merged.  My only question is whether the classical locus is actually "FT" as stated in the YML document.  I don't believe that I can find an actual classical locus name in the publication and my searches elsewhere only indicate it was a "florigen" and was associated with other genes with classical names E1, E2, and E3.  I can try to find the document "Palmer RG, Pfeiffer TW, Buss GR, Kilen TC. Qualitative genetics Soybeans: improvement, production, and uses. 3rd ed. Madison (WI): ASA, CSSA, and SSSA; 2004. p. 137–214" and search for it there.

**Comment by ScottKalberer** [comment]
I have now talked to Steven Cannon over the phone and we have decided to remove the classical locus field.

**Review by ScottKalberer — APPROVED** [review]
I have reviewed and approved this gene function study and will now merge the glyma.Su_Chen_2022 branch into the main branch.

**Pull request merged**
