### PR TITLE
Create glyma.Sugawara_Umehara_2019

### PR DESCRIPTION
**Pull request by ellatownsend90**
first attempt on this article

### CODE REVIEW

**Comment by ScottKalberer** [comment]
A few quick comments before we get too far here.  When you have a citation with three or more authors [such as Sugawara, Umehara et al, 2019] the format would be "LastName, LastName et al., YEAR".  So there is a period at the end of "al", as in "et al.", because "et al." - which just means "and others" in Latin - is a shortened form of "et alii" for a group of men or a mixed group of men and women, or "et aliae" if the non-named authors all were women.  So shortening the phrase to "et al." saves space and the need to figure out Latin grammatical gender rules.  Some style manuals have you drop all the periods and italics on these sorts of latin abbreviations, which would recognize that we use them as English words and in fact do not understand Latin, but as far as I know that isn't as common in plant sciences.

**Comment by ScottKalberer** [comment]
Also, when we list the gene symbols there isn't a name directly after the "gene_symbols:" top-level key like you have in this file as "gene_symbols: RJ2".  Each gene_symbol would be listed after a dash and space in an array of key-value pairs like in the example below, even if there is in fact only one gene_symbol.  Furthermore, normally the gene symbol gets a genus-species prefix in front even if the paper didn't use such a format, in this case "Gm" for Glycine max.  Let me know if this formatting isn't clear yet.

gene_symbols:
  - GmRJ2

**Review by StevenCannon-USDA — COMMENTED** [review]
I agree with Scott's comments.

For the gene_model_full_id: the assembly 1 gene ID is acceptable, but I'd like to standardize on assembly 4 when such a gene is available. That gene here is `glyma.Wm82.gnm4.ann1.Glyma.16G212300`
See the gene tree: 
https://funnotate.legumeinfo.org/?family=L_01CW53&gene_name=glyma.Wm82.gnm4.ann1.Glyma.16G212300

For confidence: let's use 5. They tested using a complementation test and by examining responses in 79 soybean accessions. They established that a single base change is responsible for the observed compatibility/incompatibility phenotype.

Comments: the convention is that a upper-cased gene symbol refers to the dominant allele and lower-cased symbol refers to the recessive allele, so the comment about the dominant/recessive symbols doesn't add information. Instead, let's use:
```
  - Cultivated soybean carrying the Rj2 allele restricts nodulation with specific Bradyrhizobium strains via host immunity, mediated by rhizobial type III secretory protein NopP and the host resistance protein Rj2. 
  - The Rj2 gene appears to have been maintained during the process of soybean domestication to adapt to high rhizobial diversity.
```

The synopsis needs to be more accurate, precise, and informative. How about:
```
  - The Rj2 protein mediates compatibility with rhizobial strains. 
```

**Comment by ScottKalberer** [comment]
There are currently two YML documents created for this same paper: glyma.Sugawara_Umehara_2019 by Ella Townsend and  glyma.Sugawara_Umehara_2019.yml by Greg Murrell.  Possibly Greg's work on this publication was not clear in the curation spreadsheet and it was overlooked.  My plan is to remove the file without the YML suffix, incorporate work from Ella's file regarding ontologies into Greg's file, and list both as curators in the resulting file.  Then I will start making the corrections suggested by the reviewers and get us to a point where the branch can be merged.

**Comment by ScottKalberer** [comment]
glyma.Sugawara_Umehara_2019
---
scientific_name: Glycine max
gene_symbols: RJ2
  -
gene_symbol_long:
gene_model_pub_name: Glyma16g33780
gene_model_full_id: glyma.Wm82.gnm1.ann1.Glyma16g33780
confidence: 3
curators:
  - Ella Townsend
comments:
  - has a recessive and dominant alleles dominant RJ2 and rj2
phenotype_synopsis: a gene responsible for the immunity to or the formation of root nodules
traits:
  - entity_name: nodulation
  - entity: GO:0009877
  - entity_name: root hair
  - entity: GO:0035618
references:
  - citation: Sugawara, Umehara et al, 2019
    doi: 10.1371/journal.pone.0222469
    pmid: 31518373


glyma.Sugawara_Umehara_2019.yml
---
scientific_name: Glycine max
gene_symbols:
  - GmRj2
gene_symbol_long: Restriction of nodulation 2
gene_model_pub_name: Glyma16g33780
gene_model_full_id: glyma.Wm82.gnm1.ann1.Glyma16g33780
confidence: 4
curators:
  - Greg Murrell
phenotype_synopsis: Some alleles of Rj2 restrict nodulation to specific rhizobial strains.
traits:
  - entity_name: root nodule
    entity: PO:0003023
references:
  - citation: Sugawara, Umehara et al., 2019
    doi: 10.1371/journal.pone.0222469
    pmid: 31518373

**Review by StevenCannon-USDA — APPROVED** [review]
I concur with the merger of these two files, and with Scott's edits. Will approve and merge to main.

**Pull request merged**
