### PR TITLE
Greg

### PR DESCRIPTION
**Pull request by JGregM**
Several yaml files in need of review.

### CODE REVIEW

**Review by StevenCannon-USDA — CHANGES_REQUESTED** [review]
Please add gene_model_full_id
And for the first trait entry, let's use a plant height term from TO (plant trait ontology)

**Review by StevenCannon-USDA — COMMENTED** [review]
Please add gene_model_full_id.
For traits, please restructure into related groups, like this:
```
  - entity_name: salt tolerance
    entity: TO:0006001
    relation_name: positively regulates
    relation: RO:0002213
  - entity_name: response to osmotic stress
    entity: GO:0006970
    relation_name: positively regulates
    relation: RO:0002213
```
If possible, use a term from TO in preference to CO_336 -- i.e., `drought tolerance`

**Comment by JGregM** [comment]
Changes made. Requesting review.

**Review by StevenCannon-USDA — APPROVED** [review]
Needs gene_model_full_id. I'll approve and add it.

**Pull request merged**
