### PR TITLE
Add glyma.Qian_Jin_2022

### PR DESCRIPTION
**Pull request by weihuang12**
Added New glyma.Qian_Jin_2022 to gene-function-registry

Updated glyma.Fang_Li_2014.yml

### CODE REVIEW

**Review by StevenCannon-USDA — COMMENTED** [review]
The content for the Qian, Jin et al. paper mostly looks good to me, but I request the following edits:

- Comments are needed in the branch and/or PR to explain the reason for deleting glyma.Du_Zhao_2018.yml 
- The first citation in each of the two yaml documents should be the main paper for these genes, i.e. "Qian, Jin et al., 2022". Any other citations would be included as supporting evidence for the gene in that document. You can repeat citations across multiple documents -- and in fact, "Qian, Jin et al., 2022" must appear in both.
- Each citation should include the year and have this form: "Author1, Author2 et al., YEAR"
- The DOI for Shi, You-Xin et al. seems not to be valid.
- The citation for `Xie, Hongtao et. al.` should instead be `Xie, Song et al., 2022"
- If a PMID is not available, the pmid line should be omitted rather than "null". However, it looks like there is a pmid at least for 10.1111/jipb.13631 : 35456933. You can check these at https://pubmed.ncbi.nlm.nih.gov
- The citation for Juwattanasomran should have the form "Author1, Author2 et al., YEAE"

**Comment by weihuang12** [comment]
Thanks for the review @StevenCannon-USDA.

 As for **The DOI for Shi, You-Xin et al. seems not to be valid.**

I don't know why the DOI didn't work. It provides by the paper. If I input the doi in the browser, the correct paper appears, but if I click on the doi link, it shows error message. Should I just remove this citation in the yaml file?

**Comment by StevenCannon-USDA** [comment]
It looks to me like it this is the citation:
Shi, W., Yang, Y., Chen, S. et al. Discovery of a new fragrance allele and the development of functional markers for the breeding of fragrant rice varieties . Mol Breeding 22, 185–192 (2008). https://doi.org/10.1007/s11032-008-9165-7

... which would be entered this way (and there is no pmid):
```
  - citation: Shi, Yang et al., 2008
    doi: 10.1007/s11032-008-9165-7
```

**Comment by weihuang12** [comment]
@StevenCannon-USDA 
**Comments are needed in the branch and/or PR to explain the reason for deleting glyma.Du_Zhao_2018.yml**
I chose a paper by Du, Zhao et. al 2018 from the spreadsheet list,  and created a branch on repo gene-function-registry, but then realized that this paper has already been worked on by someone, so I deleted the branch, but possible mistakenly deleted the glyma.Du_Zhao_2018.yml
Can we recover the deleted glyma.Du_Zhao_2018.yml file?

**Comment by StevenCannon-USDA** [comment]
> Can we recover the deleted glyma.Du_Zhao_2018.yml file?

I see. Yes, no problem.

If the deletion had been done as a single commit, that commit could be rolled back, but I don't think that's possible if it was part of a single combined commit.

So, probably the easiest thing will be for you to add the contents of that file as a new yaml document, with that filename (glyma.Du_Zhao_2018.yml), and push that as part of this PR. I think when you do `git status` locally, you will see no change with respect to that file -- but I am not sure. (You can get the contents either from the `main` branch or by viewing the deleted file in this PR).

**Comment by weihuang12** [comment]
@StevenCannon-USDA  I have updated glyma.Qian_Jin_2022.yml based on your review.
I have also added glyma.Du_Zhao_2018.yml under this branch and pushed it as part of the pull request.
Thanks for the detailed instructions and review.

**Review by StevenCannon-USDA — APPROVED** [review]
Thanks, Wei. This version looks good to me. Will merge to main.

**Pull request merged**
