### PR TITLE
Add missing 2023 records

### PR DESCRIPTION
**Pull request by StevenCannon-USDA**
Continuation of the "add-missing" branch from two days ago, with addition of combined/derived files under gene_functions for each species (gensp.citations.txt and gensp.traits.yml).

### CODE REVIEW

**Review by maxglycine — CHANGES_REQUESTED** [review]
@StevenCannon-USDA @jd-campbell @ChenProm-USDA Was unable to view branch.  YAML Lint failded, trailing spaces

**Comment by StevenCannon-USDA** [comment]
>  YAML Lint failded, trailing spaces

I believe I've fixed the yml. The files validate for me locally. The check during the GitHub action appears to be failing due to a package problem at GitHub.

**Review by ScottKalberer — APPROVED** [review]
I didn't see any glaring problems following a cursory overview of these changes.  If the underlying YML files were accurate than the derived files should be too assuming there aren't formatting problems.

**Review by maxglycine — APPROVED** [review]
Assuming all of the YAML files passed the LINT validator because I not going to attempt to re-validate any.  That is the only thing I can think of to decide if the changes should be approved.  Assuming that the YAML was validated and approving it

**Pull request merged**
