### PR TITLE
Added Glycine max studies that had been in glyma.traits.yml 

### PR DESCRIPTION
**Pull request by StevenCannon-USDA**
… but not in separate per-study yml files.

@ScottKalberer and @jd-campbell -- I'd like to get these files merged quickly, to get them into the system and comparable with the tracking spreadsheet. They were ones that we did early-on, prior to the current practice of basing branches on a primary publication per-study. Most of these are ones that I did, so they are probably reasonably solid. We can do a more careful evaluation later.

So, if you would ... please one of you do the review and merge to main -- unless you find things that should be fixed at this stage prior to merging.

### CODE REVIEW

**Comment by StevenCannon-USDA** [comment]
Changing this PR to draft status until I finish adding the other species.

**Comment by StevenCannon-USDA** [comment]
@ScottKalberer and @jd-campbell -- Ready for (top-level) review.

**Comment by ScottKalberer** [comment]
The Medicago truncatula studies, they were in medtr.traits.yml rather than glyma.traits.yml, correct?

**Comment by StevenCannon-USDA** [comment]
> The Medicago truncatula studies, they were in medtr.traits.yml rather than glyma.traits.yml, correct?

Yes, that is correct.

**Review by ScottKalberer — APPROVED** [review]
I have completed some minor alterations and approved this merge into the main branch.

**Pull request merged**
