### PR TITLE
Revisions to glyma.Wang_Guo_2021.yml on 31 October 2024

### PR DESCRIPTION
**Pull request by ScottKalberer**
I've corrected the gene_function_registry file glyma.Wang_Guo_2021.yml originally created by Marlena Dorneich-Hayes. I created the new branch glyma.Wang_Guo_2021 with this revised file and pushed it up to the GitHub origin. I'm requesting review of this YML gene function file, merge of the changes into main branch, and subsequent deletion of this temporary branch on GitHub.

### CODE REVIEW

**Review by StevenCannon-USDA — COMMENTED** [review]
Good catch on correction of the prior gene_model_pub_name.
I concur: 
GmSTF3: glyma.Wm82.gnm2.ann1.Glyma.16G092700 == glyma.Wm82.gnm6.ann1.Glyma.16G092700

The other TGACG-sequence-specific DNA-binding protein discussed is 
GmSTF4: glyma.Wm82.gnm2.ann1.Glyma.03G081700 == glyma.Wm82.gnm6.ann1.Glyma.03G081700

The gene family (current family view and new one, not yet public):
https://funnotate.legumeinfo.org/?family=legfed_v1_0.L_GQ0S25
http://dev.lis.ncgr.org:50082/?family=Legume.fam3.13265

The Arabidopsis HY5 homolog, AT3G17609:
https://www.arabidopsis.org/locus?name=AT3G17609

If GmSTF3 (Glyma.16G092700) and GmFT2a (Glyma.16G15070) are included for this study, I am thinking that GmSTF4 (Glyma.03G081700) should also be included (as another sub-document for this study).

I am not sure though. It depends whether a phenotype is reported for GmSTF4; but it is likely essentially the same as GmSTF3 -- as a recent WGD-derived paralog.

So I think the suggestion is: to add a section for GmSTF4 (Glyma.03G081700).

**Comment by ScottKalberer** [comment]
I have looked through this paper again and I'm not sure what to do with GmSTF4.  Perhaps I will add it to the YML for completeness sake, but provide a low confidence score?  Soybean TGACG-motif binding factor 4 (GmSTF4) and GmSTF3 are mainly expressed in the leaves, unlike GmSTF1 and GmSTF2 which were expressed in both leaves and roots.  They created a CRISPR-Cas9 GmSTF3/4-CR knockout line with mutations in each of the two genes that was used in the experiments, but they only look for STF3 in the roots of the stock after grafting, only looked for STF3 in phloem sap, and hence only showed that STF3 moved from the shoots to the roots.  Nodule formation was enhanced in the overexpression line GmSTF3-OE and reduced in the knockout lines GmSTF3/4-CR - there was no GmSTF4 over expression line.  When shoots of the GmSTF3/4-CR lines were used as donor scions in grafts (GmSTF3/4-CR onto GmSTF3/4-CR or wild type), none of the knockout grafts nodulated like grafts with wild-type donors.

**Comment by ScottKalberer** [comment]
I find this comment confusing - why are they talking about protein levels of GmSTF3 and then invoke a GmSTF3/4 mobile signal as if anything said about STF3 may be assumed to be true of STF4?  "In addition, the protein levels of GmSTF3 and GmFT2a
in roots under different light conditions and in the roots of the GmCRY1s transgenic lines
were positively correlated with nodule formation (fig. S7). Thus, both GmSTF3/4 and GmFTs are shoot-derived, light-induced mobile signals that regulate soybean nodule formation."

**Comment by ScottKalberer** [comment]
As I mention in the comments "After migration, STF3 is phosphorylated by calcium/calmodulin-dependent protein kinase (GmCCaMK), which is activated by rhizobial infection of the roots.  Phosphorylation causes GmSTF3 and GmFT2a to form a complex that subsequently activates gene expression of nodulation signaling pathway 1 (GmNSP1), nodule inception (GmNIN), and nuclear factor Y (GmNF-YA1 and GmNF-YB1)."  The authors do not examine whether STF4 was phosphorylated by CCaMK, or whether it forms a complex with FT2a, or show that said complex activates a downstream nodulation signaling pathway.  I think all we can describe is the dysfunction caused by knocking out both STF3 and STF4 simultaneously in the grafting experiments.

**Comment by ScottKalberer** [comment]
Yet in this review by Yue, Pei et al. (2023) [https://doi.org/10.3389/fpls.2023.1150363] they seem to accept the concept that STF4 has been shown to function in this nodulation pathway.  "Wang et al. (2021) demonstrated that light-induced STF3/GmbZIP131, STF4/GmbZIP20, and GmFTs interdependently induce nodule organogenesis from shoots to roots. The rhizobium-activated calcium- and calmodulin-dependent protein kinase (CCaMK) phosphorylates STF3/GmbZIP131, triggering STF3/GmbZIP131-FT2a complex formation, which directly activates GmNIN and Nuclear factor Y (GmNF-YA1 and GmNF-YB1) expression. The GmCCaMK-STF3/GmbZIP131-STF4/GmbZIP20-FT module integrates the light-induced shoot signal and the rhizobium-activated root signal, which coordinately promote nodule formation ([Figure 2E]". Am I being excessively skeptical, have I missed evidence provided in the paper or supplementary files, or is the wording in the paper misleading me somehow?

**Comment by StevenCannon-USDA** [comment]
@ScottKalberer - thanks for the care and skepticism with this one. I don't know the right thing to do regarding STF3. It's clearly part of a complex process, and teasing apart the roles of the various players is made more difficult due to the number of participants in the dance. I am content to leave it as it stands. I did make one change, though: For the gene_model_full_id, change from gnm6 to gnm4, as gnm4 will be the representative annotation in several SoyBase/LIS tools through 2025.
Will now approve, merge, and delete.

**Review by StevenCannon-USDA — APPROVED** [review]
Approving after changing gene_model_full_id to gnm4

**Pull request merged**
